server:
  port: ${PORT:10000}
  servlet:
    context-path: /api

spring:
  application:
    name: jg-nexus

  datasource:
    url: jdbc:postgresql://dpg-d6vnktn5r7bs73etm99g-a/jg_nexus
    username: jg_nexus_user
    password: wu3KVOgktt5b11LTLcUqsn0p0XYq8baQ
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

  cache:
    type: redis

jwt:
  secret: ${JWT_SECRET:jgNexusSecretKey2026}
  expiration: 86400000
  refresh-expiration: 604800000

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:*}
